stages:
 - deploy


deploy_digitalocean_prod:
    type: deploy
    image: ubuntu
    environment: production
    script:
      - apt update -y
      - apt install -y sshpass
      - mkdir ../tumanaapi
      - chmod -R +r ../tumanaapi
      - cp -r . ../tumanaapi
      - sshpass -p $SERVER_TOCKEN scp -o stricthostkeychecking=no -r ../tumanaapi/ ian@$64.225.43.150:/ian/.
      - sshpass -p $SERVER_TOCKEN ssh -o StrictHostKeyChecking=no ian@$64.225.43.150 "cd tumanaapi; npm i; export NODE_ENV=production; export PORT=3000; export HOST=127.0.0.1; npm run build; pm2 delete tumanaapi; pm2 start 'dist/main.js' --name 'tumanaapi';"
    only:
      - master


deploy_digitalocean_testing:
    type: deploy
    image: ubuntu
    environment: development
    script:
      - apt update -y
      - apt install -y sshpass
      - mkdir ../tumanatestingapi
      - chmod -R +r ../tumanatestingapi
      - cp -r . ../tumanatestingapi
      - sshpass -p $SERVER_TOCKEN scp -o stricthostkeychecking=no -r ../tumanatestingapi/ root@$SERVER_IP:/root/.
      - sshpass -p $SERVER_TOCKEN ssh -o StrictHostKeyChecking=no root@$SERVER_IP "cd tumanatestingapi; npm i; export NODE_ENV=development; export PORT=4000; export HOST=127.0.0.1; npm run build; pm2 delete tumanatestingapi; pm2 start 'dist/main.js' --name 'tumanatestingapi';"
    only:
      - testing
